name: Code review with AI

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Validate Secrets
        run: |
          if [ -z "${{ secrets.token_github }}" ] || [ -z "${{ secrets.open_arena_token }}" ]; then
            echo "Missing required secrets (token_github or open_arena_token). Exiting."
            exit 1
          fi
          echo "All required secrets are available."

      - name: Run Code review with AI
        env:
          TOKEN_GITHUB: ${{ secrets.token_github }}
          OPEN_ARENA_TOKEN: ${{ secrets.open_arena_token }}
          GITHUB_PR_URL: ${{ github.event.pull_request.url }}
          WORKFLOW_ID: "8556ba87-acf8-4049-98a3-fc62a300656c"  # Replace with your actual workflow ID
        run: python3 scripts/ai_code_reviewer.py
